sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=s390x

script:
  - ./travis-build.sh
  - >
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # push image on master and non-pull-request builds
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi