sudo: required

services:
 - docker

secure: "migRCM05O53vDs25shSWHLt9pbk5SMJeFmPD42mwdThEoASYPaQ2iUoijU3kfkK8WYbtMdwfKJbvsKfPUtMPtMOvk+ithRhDXeK2aF4lhw33QK2E07sGlAGv8S6BTrX9V6G82INWqUezhl3j6kclCgDTOP5uAVdSGb0RvBR+xiGIyGdqx6sh01JfiN9YWWaEVqqu3y0rFBpIPc9ihzogSCxU1L1CrFkpiLtTh4C5yrGJmYDZvhzAW2LWuPFCIBLr9EgyKAAIgndXmy4iEr9nHJpdB82rFOJgIFuC2SSEwY2Bt4qxnbLBiQF+NfefSDmlLe6heQvu6vIbnAJT7dg9Rq7Kky33YH8eyh/rGOovOc1WEUYNFJgJ2yvKN+5EeM8kp9epXT6GD189xBomYHxk+9qaP1lEQ/IK2niQvkl1PBSmaxWKdODf+i+6jrWkGOhMnI//eXXgQZP9iKm5T3bWf7KQdgAuQcYJhdQurPsdiZU8i0Br/VPUDeBI0m5vHcUG5sPLdYpe5W48pHsVw1UtUTPsGlq9sBI2p1mLQ0RYXOx+HEspH2C5HnKI9fc5szc34KRWUMPDsxtDyvz1DeIHlBZGDJzB5DdLeaQsvjcbemGXF8bfazFrLbZ5OJTdeVNL+XF9eeQTpLf35YG5DiRS00gxgrx3xITQQs7rHtZ2Jfc="

env:
  matrix:
    - ARCH=amd64
    - ARCH=s390

script:
  - ./travis-build.sh
  - >
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # push image on master and non-pull-request builds
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi